env:
  es6: true
  mocha: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 6
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  no-console:
    - 0
  quotes:
    - error
    - single
  semi:
    - error
    - never
  space-before-function-paren:
    - error
    - never
